# Generated by Django 2.1 on 2018-08-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
    ]
