# Generated by Django 2.1 on 2018-08-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotLocator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='logitude',
            new_name='longitude',
        ),
    ]
