# Generated by Django 2.1 on 2018-08-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotLocator', '0002_auto_20180824_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='imageURL',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
