# Generated by Django 2.1 on 2018-08-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotLocator', '0005_auto_20180824_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='cycling',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='fishing',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='hiking',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='mtnBiking',
        ),
        migrations.AddField(
            model_name='activity',
            name='ativity',
            field=models.CharField(choices=[('Road-Cycling', 'Road-Cycling'), ('Mountain Biking', 'Mountain Biking'), ('Hiking', 'Hiking'), ('Fishing', 'Fishing'), ('Climbing', 'Climbing')], default='Fishing', editable=False, max_length=15),
        ),
    ]
