# Generated by Django 2.1 on 2018-08-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotLocator', '0006_auto_20180824_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='activityType',
            new_name='activity',
        ),
        migrations.AlterField(
            model_name='activity',
            name='ativity',
            field=models.CharField(choices=[('Road-Cycling', 'ROADCYCLE'), ('Mountain Biking', ' MTNBIKE'), ('Hiking', 'HIKE'), ('Fishing', 'FISH'), ('Climbing', 'CLIMB')], default='Fishing', editable=False, max_length=15),
        ),
    ]
