# Generated by Django 2.1 on 2018-08-24 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotLocator', '0007_auto_20180824_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='ativity',
            new_name='activity',
        ),
    ]
