# Generated by Django 2.1 on 2018-08-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotLocator', '0009_auto_20180824_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='activity',
        ),
        migrations.AddField(
            model_name='spot',
            name='color',
            field=models.CharField(choices=[('RED', 'red'), ('WHITE', 'white'), ('BLUE', 'blue')], default='RED', max_length=5),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
