# Generated by Django 2.1 on 2018-08-24 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotLocator', '0010_auto_20180824_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('ROADCYCLE', 'Road-Cycling'), ('MTNBIKE', ' Mountain Biking'), ('HIKE', 'Hiking'), ('FISH', 'Fishing'), ('CLIMB', 'Rock Climbing')], default='FISH', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='spot',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spotLocator.Activity'),
        ),
    ]
