# Generated by Django 2.1 on 2018-08-29 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotLocator', '0012_auto_20180824_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='active',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spotLocator.Spot'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(choices=[('ROADCYCLE', 'Road-Cycling'), ('MTNBIKE', ' Mountain Biking'), ('HIKE', 'Hiking'), ('FISH', 'Fishing'), ('CLIMB', 'Rock Climbing')], default='FISH', max_length=15),
        ),
    ]
