# Generated by Django 2.1 on 2018-10-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotLocator', '0016_auto_20181001_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
