# Generated by Django 2.1 on 2018-10-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotLocator', '0017_auto_20181001_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='activity',
            field=models.CharField(choices=[('Road-Cycling', 'Road-Cycling'), ('Mountain Biking', ' Mountain Biking'), ('Hiking', 'Hiking'), ('Fishing', 'Fishing'), ('Rock Climbing', 'Rock Climbing')], default='FISH', max_length=15),
        ),
    ]
